# encoding: UTF-8
module TestUtil
  # MT-unsafe
  def self.require(dir, *features)
    begin
      # avoid 'already initialized constant FizzBuzz' warning
      silent do
        $:.unshift(dir)
        features.each do |feature|
          Kernel.require feature
        end
        $:.shift
      end
    ensure
      features.each do |feature|
        $".delete(feature)
      end
    end
  end

  # MT-unsafe
  def self.silent
    if $DEBUG
      yield
    else
      back = $VERBOSE
      $VERBOSE = nil
      begin
        yield
      ensure
        $VERBOSE = back
      end
    end
  end

  def self.filecompare(expectedfile, actualfile)
    expected = loadfile(expectedfile)
    actual = loadfile(actualfile).lines.reject{|l| l =~ /^# Generated by/}.join # Must be filtered out, as this will change by Version Number anyway.
    if expected != actual
      raise "#{File.basename(actualfile)} is different from #{File.basename(expectedfile)}"
    end
  end

  def self.loadfile(file)
    File.open(file) { |f| f.read }
  end

  def self.start_server_thread(server)
    t = Thread.new {
      Thread.current.abort_on_exception = true
      server.start
    }
    t
  end

  def self.webrick_http_server(options)
    webrick_server(WEBrick::HTTPServer, options)
  end

  def self.webrick_proxy_server(options)
    webrick_server(WEBrick::HTTPProxyServer, options)
  end

  def self.webrick_server(klass, options)
    try = 0
    begin
      klass.new(options)
    rescue Errno::EADDRINUSE => e
      STDERR.puts "Wait for available port for #{klass.name} (#{e.message}) [#{Thread.list.inspect}]"
      sleep 1
      # Confirmed via GitHub Actions logs (run 28849464390, Ruby 2.2 job) that
      # a busy shared runner can hold port 17171 for 45+ seconds across a
      # whole run of back-to-back tests (test_digest -> test_calc ->
      # test_calc2 -> test_calc_cgi -> test_customfault all failed in
      # sequence), well past the 10s budget that sufficed locally. 60 tries
      # (60s) wasn't always enough either -- confirmed via run 28861909674
      # (Ruby 2.6.10/2.7.8) still hitting isolated EADDRINUSE on this exact
      # retry-wrapped path even at 60 tries. Widened further to 120 (2min);
      # this only bounds an already-rare CI-only flake, not a hot path.
      ((try += 1) < 120) ? retry : raise(e)
    end
  end
end
