# encoding: UTF-8
module TestUtil
  # MT-unsafe
  def self.require(dir, *features)
    begin
      # avoid 'already initialized constant FizzBuzz' warning
      silent do
        $:.unshift(dir)
        features.each do |feature|
          Kernel.require feature
        end
        $:.shift
      end
    ensure
      features.each do |feature|
        $".delete(feature)
      end
    end
  end

  # MT-unsafe
  def self.silent
    if $DEBUG
      yield
    else
      back = $VERBOSE
      $VERBOSE = nil
      begin
        yield
      ensure
        $VERBOSE = back
      end
    end
  end

  def self.filecompare(expectedfile, actualfile)
    expected = loadfile(expectedfile)
    actual = loadfile(actualfile).lines.reject{|l| l =~ /^# Generated by/}.join # Must be filtered out, as this will change by Version Number anyway.
    if expected != actual
      raise "#{File.basename(actualfile)} is different from #{File.basename(expectedfile)}"
    end
  end

  def self.loadfile(file)
    File.open(file) { |f| f.read }
  end

  def self.start_server_thread(server)
    t = Thread.new {
      Thread.current.abort_on_exception = true
      server.start
    }
    t
  end

  def self.webrick_http_server(options)
    webrick_server(WEBrick::HTTPServer, options)
  end

  def self.webrick_proxy_server(options)
    webrick_server(WEBrick::HTTPProxyServer, options)
  end

  # Extracts the request body XML out of a wiredump_dev capture. Every HTTP
  # client backend (see lib/soap/httpbackend.rb) writes the same block
  # layout -- "Wire dump:", "= Request", the raw request-line+headers, the
  # body, "= Response", the raw response-line+headers, the response body --
  # separated by blank lines, so the body is always the 4th block (index 3)
  # regardless of which backend produced the dump. This was confirmed by
  # design, not by accident: SOAP::NetHttpClient/CurbClient/FaradayClient
  # were all built to match httpclient's own block layout exactly (see the
  # "Mirrors httpclient's wiredump block layout" comments in
  # lib/soap/netHttpClient.rb, curbClient.rb, and faradayClient.rb) precisely
  # so callers like this one don't need to special-case any of them.
  def self.parse_wiredump_request_body(str)
    str.split(/\r?\n\r?\n/)[3]
  end

  # Same deal, for the response body (block index 6 -- see
  # parse_wiredump_request_body above for the full block layout).
  def self.parse_wiredump_response_body(str)
    str.split(/\r?\n\r?\n/)[6]
  end

  def self.webrick_server(klass, options)
    try = 0
    begin
      klass.new(options)
    rescue Errno::EADDRINUSE => e
      STDERR.puts "Wait for available port for #{klass.name} (#{e.message}) [#{Thread.list.inspect}]"
      sleep 1
      # This budget got widened all the way to 120 (2min) chasing what
      # turned out to be a real leak: several test teardown methods called
      # Thread#kill immediately after WEBrick's own shutdown, racing its
      # async listener cleanup and occasionally leaving the port bound (see
      # the removed .kill calls across 36 test files). With that fixed, this
      # only needs to cover genuine transient scheduling delay on a busy
      # runner, not a real leak -- and a large budget here is actively
      # harmful now: compounded across several tests in one run it produces
      # multi-minute *hangs* rather than fast, visible failures (confirmed:
      # run 28892185757 stalled 20+ minutes with several retries stacking).
      # Pulled back down to 20s, comfortably above what transient delay
      # needs, far below what turns a rare miss into a CI-wrecking stall.
      ((try += 1) < 20) ? retry : raise(e)
    end
  end
end
