<?xml version="1.0"?>
<definitions name="SOAP4R_SOAPBuildersInteropTest_R2GroupB"
    targetNamespace="http://soapinterop.org/"
    xmlns:tns="http://soapinterop.org/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

<import
    namespace="http://soapinterop.org/"
    location="http://www.whitemesa.com/interop/InteropTestB.wsdl"/>

<portType name="InteropTestPortTypeB_wo_outParam">
  <operation name="echoSimpleTypesAsStruct"
      parameterOrder="inputString inputInteger inputFloat">
    <input name="echoSimpleTypesAsStruct"
	message="tns:echoSimpleTypesAsStructRequest"/>
    <output name="echoSimpleTypesAsStructResponse"
	message="tns:echoSimpleTypesAsStructResponse"/>
  </operation>

  <operation name="echo2DStringArray"
      parameterOrder="input2DStringArray">
    <input name="echo2DStringArray"
	message="tns:echo2DStringArrayRequest"/>
    <output name="echo2DStringArrayResponse"
	message="tns:echo2DStringArrayResponse"/>
  </operation>

  <operation name="echoNestedStruct"
      parameterOrder="inputStruct">
    <input name="echoNestedStruct"
	message="tns:echoNestedStructRequest"/>
    <output name="echoNestedStructResponse"
      message="tns:echoNestedStructResponse"/>
  </operation>

  <operation name="echoNestedArray"
      parameterOrder="inputStruct">
    <input name="echoNestedArray"
	message="tns:echoNestedArrayRequest"/>
    <output name="echoNestedArrayResponse"
	message="tns:echoNestedArrayResponse"/>
  </operation>
</portType>

<binding name="InteropTestSoapBindingB_wo_outParam"
    type="tns:InteropTestPortTypeB_wo_outParam">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

  <operation name="echoSimpleTypesAsStruct">
    <soap:operation soapAction=""/>
    <input>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </input>
    <output>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </output>
  </operation>

  <operation name="echo2DStringArray">
    <soap:operation soapAction=""/>
    <input>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </input>
    <output>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </output>
  </operation>

  <operation name="echoNestedStruct">
    <soap:operation soapAction=""/>
    <input>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </input>
    <output>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </output>
  </operation>

  <operation name="echoNestedArray">
    <soap:operation soapAction=""/>
    <input>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </input>
    <output>
      <soap:body
	  use="encoded"
	  namespace="http://soapinterop.org/"
	  encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </output>
  </operation>
</binding>

<service name="SOAP4R_SOAPBuildersInteropTest_R2GroupB">
  <port name="InteropTestSoapPort_wo_outParam"
      binding="tns:InteropTestSoapBindingB_wo_outParam">
    <soap:address
	location="http://www.jin.gr.jp/~nahi/Ruby/SOAP4R/SOAPBuildersInterop/"/>
  </port>
</service>

</definitions>
