#!/bin/sh -

ruby clientSOAP4R.rb
ruby client.NetRemoting.rb
ruby client4S4C.rb
ruby client4S4C2.rb
ruby clientASP.NET.rb
ruby clientApacheAxis.rb
ruby clientApacheSOAP.rb
ruby clientCapeConnect.rb
ruby clientDelphi.rb
ruby clientEasySoap.rb
ruby clientFrontier.rb
ruby clientGLUE.rb
ruby clientHP.rb
ruby clientJSOAP.rb
ruby clientMSSOAPToolkit2.0.rb
ruby clientMSSOAPToolkit3.0.rb
ruby clientNuSOAP.rb
ruby clientOpenLink.rb
ruby clientPEAR.rb
ruby clientPhalanx.rb
ruby clientSIMACE.rb
ruby clientSOAP::Lite.rb
ruby clientSQLData.rb
ruby clientSoapRMI.rb
ruby clientSpray2001.rb
ruby clientWASP.rb
ruby clientWASPC.rb
ruby clientWhiteMesa.rb
ruby clientSilverStream.rb
ruby clientXMLBus.rb
ruby clienteSOAP.rb
ruby clientgSOAP.rb
ruby clientkSOAP.rb

#ruby clientXMLRPC-EPI.rb
#ruby clientZSI.rb
