#!/bin/sh -

/home/nahi/bin/ruby clientSOAP4R.rb

/home/nahi/bin/ruby client4S4C.rb
/home/nahi/bin/ruby client4S4C2.rb
/home/nahi/bin/ruby clientApacheAxis.rb
/home/nahi/bin/ruby clientApacheSOAP.rb
/home/nahi/bin/ruby clientASP.NET.rb
/home/nahi/bin/ruby clientBEAWebLogic.rb
#/home/nahi/bin/ruby clientCapeConnect.rb
/home/nahi/bin/ruby clientDelphi.rb
/home/nahi/bin/ruby clientEasySoap.rb
/home/nahi/bin/ruby clienteSOAP.rb
/home/nahi/bin/ruby clientgSOAP.rb
/home/nahi/bin/ruby clientFrontier.rb
/home/nahi/bin/ruby clientGLUE.rb
/home/nahi/bin/ruby clientHP.rb
#/home/nahi/bin/ruby clientXMLBus.rb
/home/nahi/bin/ruby clientKafkaXSLT.rb
/home/nahi/bin/ruby clientkSOAP.rb
/home/nahi/bin/ruby client.NetRemoting.rb
/home/nahi/bin/ruby clientMSSOAPToolkit2.0.rb
/home/nahi/bin/ruby clientMSSOAPToolkit3.0.rb
/home/nahi/bin/ruby clientNuSOAP.rb
/home/nahi/bin/ruby clientNuWave.rb
/home/nahi/bin/ruby clientOpenLink.rb
/home/nahi/bin/ruby clientOracle.rb
/home/nahi/bin/ruby clientPEAR.rb
#/home/nahi/bin/ruby clientPhalanx.rb
#/home/nahi/bin/ruby clientSilverStream.rb
/home/nahi/bin/ruby clientSIMACE.rb
/home/nahi/bin/ruby clientSOAP::Lite.rb
/home/nahi/bin/ruby clientJSOAP.rb
/home/nahi/bin/ruby clientSpray2001.rb
/home/nahi/bin/ruby clientSQLData.rb
/home/nahi/bin/ruby clientSun.rb
/home/nahi/bin/ruby clientVWOpentalkSoap.rb
/home/nahi/bin/ruby clientWASP.rb
/home/nahi/bin/ruby clientWASPC.rb
/home/nahi/bin/ruby clientWebMethods.rb
/home/nahi/bin/ruby clientWhiteMesa.rb
/home/nahi/bin/ruby clientWingfoot.rb
#/home/nahi/bin/ruby clientSoapRMI.rb

# Permanent
#/home/nahi/bin/ruby clientTclSOAP.rb
#ruby clientXMLRPC-EPI.rb
#ruby clientZSI.rb
